### PR TITLE
Add generic effect system tests (via casting effects)

### PR DESCRIPTION
**Pull request by csgordon**

### CODE REVIEW

**Comment by csgordon** [comment]
@rishimp What happened with the deleted methods in ```GenericEffectExtension```?

**Comment by csgordon** [comment]
The hygiene run failed (https://travis-ci.org/csgordon/checker-framework/jobs/273350164) on a check that should have run when you did ```git commit```.  Do you have pre-commit hooks disabled?

**Comment by csgordon** [comment]
Please run ```ant check-style``` and ```ant check-errorprone```

**Comment by rishimp** [comment]
I think the hygiene run failed because I had another wildcard import. My IDE likes to collapse imports sometimes.

**Pull request merged**
